In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn import datasets

In [10]:
data = datasets.load_breast_cancer()

In [22]:
x,y = data.data, data.target
dfdata = pd.DataFrame(x)
dflabels = pd.DataFrame(y)

X_train, X_test, y_train, y_test = train_test_split(dfdata, dflabels, test_size=0.2)

0
143  1
437  1
429  1
39   0
7    0
..  ..
556  1
444  0
134  0
297  0
231  1

[455 rows x 1 columns]

In [23]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
lableencoder = LabelEncoder()
y_train = lableencoder.fit_transform(y_train)
y_test = lableencoder.transform(y_test)

c:\Users\Ali Burhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Ali Burhan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [26]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

In [27]:
x_train_tensor = torch.tensor(X_train,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.float32)
x_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,dtype=torch.float32)

In [47]:
class SimpleNN(nn.Module):
    def __init__(self,x):
        self.weights = torch.rand(x.shape[1],1,dtype=torch.float32,requires_grad=True)
        self.bias = torch.ones(1,dtype=torch.float32,requires_grad=True)

    def forward(self,x):
        # print(f"shape of x is {x.shape}")
        z=  torch.matmul(x,self.weights) + self.bias
        # print(f"shape of z is {z.shape} {z}")
        return torch.sigmoid(z)
    def loss(self,y_pred,y):
        return F.binary_cross_entropy(y_pred,y)

In [65]:
simple = SimpleNN(x_train_tensor)
for i in range(1):
    result=simple.forward(x_train_tensor)
    loss = simple.loss(result, y_train_tensor.reshape(-1,1))
    print(f"{loss}")
    loss.backward()
    with torch.no_grad():
        simple.weights -= 0.1 * simple.weights.grad
        simple.bias -= 0.1 * simple.bias.grad
    simple.weights.grad.zero_()
    simple.bias.grad.zero_()
    print(f"{result} {y_train_tensor}")

14.205462455749512
tensor([[1.0887e-02],
        [1.6856e-03],
        [6.4320e-06],
        [9.2837e-01],
        [9.9988e-01],
        [1.2642e-02],
        [9.9990e-01],
        [8.5421e-01],
        [2.4673e-05],
        [7.2394e-01],
        [1.4032e-02],
        [4.6100e-02],
        [9.9990e-01],
        [1.3550e-03],
        [6.5556e-01],
        [5.5319e-02],
        [4.5755e-04],
        [5.8639e-04],
        [7.4650e-03],
        [1.7174e-04],
        [9.7550e-01],
        [5.0975e-05],
        [7.8307e-01],
        [9.9266e-01],
        [9.9941e-01],
        [1.0000e+00],
        [6.2731e-02],
        [1.4643e-01],
        [1.2867e-02],
        [9.9994e-01],
        [1.1332e-03],
        [1.3287e-04],
        [1.0000e+00],
        [6.9214e-01],
        [2.1456e-01],
        [5.9407e-07],
        [9.9955e-01],
        [8.1857e-02],
        [9.9358e-01],
        [6.7263e-04],
        [1.5675e-02],
        [1.0000e+00],
        [5.9173e-04],
        [3.8253e-04],
        [3.42

In [34]:
simple = SimpleNN(x_train_tensor)
simple.bias

tensor([1.], requires_grad=True)

In [35]:
learning_rate = 0.1
epochs = 25

In [37]:
model = SimpleNN(x_train_tensor)
model.bias

tensor([1.], requires_grad=True)