In [1]:
import torch

In [2]:
rand = torch.rand(2,3,requires_grad=True)
rand

tensor([[0.8940, 0.1765, 0.6330],
        [0.2546, 0.6434, 0.0538]], requires_grad=True)

In [3]:
y = rand.sum()

In [4]:
y.backward()
rand.shape

torch.Size([2, 3])

In [5]:
rand.grad

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
newRand = torch.ones_like(rand)
newRand

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.prod(rand)
torch.min(rand)
torch.std(rand)

tensor(0.3279, grad_fn=<StdBackward0>)

In [8]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [9]:
randondevice = torch.rand(2,3).to(device)
randondevice

tensor([[0.4885, 0.7848, 0.7236],
        [0.0582, 0.6903, 0.7393]])

In [10]:
randconv = rand.to(rand)
randconv

tensor([[0.8940, 0.1765, 0.6330],
        [0.2546, 0.6434, 0.0538]], requires_grad=True)

In [11]:
x = torch.tensor([2.00],requires_grad=True)

In [12]:
def dy_dx(x):
    return 2*x

In [13]:
y = 2*x
y.backward()
x.grad

tensor([2.])

In [14]:
newGrad = torch.tensor([2.0],requires_grad=True)
y = x**x
z = torch.sin(y)
z.backward()
x.grad

tensor([-2.4269])

In [15]:
y.grad

C:\Users\Ali Burhan\AppData\Local\Temp\ipykernel_16764\486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  y.grad


In [17]:
(2*2.0)*torch.cos(torch.tensor([4.0]))

tensor([-2.6146])