In [1]:
import torch 
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle

In [18]:
iris = load_iris()
x,y = iris.data, iris.target

In [19]:
# One-hot encode target
y = torch.eye(3)[y]  # 3 classes


In [20]:
x,y = shuffle(x,y,random_state=42)

In [21]:
x

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [22]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [24]:
x_train

array([[-1.01139534,  0.82747076, -1.25930407, -1.08327725],
       [ 0.50424033,  0.59546961,  0.49720555,  0.486058  ],
       [-0.89480798,  0.82747076, -1.31596567, -1.34483313],
       [-1.24457006, -0.10053383, -1.37262727, -1.47561106],
       [ 0.97058977,  0.13146732,  0.49720555,  0.35528006],
       [-1.1279827 , -1.26053956,  0.38388234,  0.61683594],
       [ 2.019876  , -0.10053383,  1.57377596,  1.13994769],
       [ 1.08717713,  0.36346846,  1.17714475,  1.40150357],
       [ 1.08717713, -0.56453612,  0.55386715,  0.22450213],
       [ 0.97058977,  0.13146732,  0.32722074,  0.22450213],
       [-0.31187119, -0.56453612,  0.61052875,  1.00916975],
       [-1.1279827 ,  0.13146732, -1.31596567, -1.34483313],
       [-0.07869647, -0.56453612,  0.72385195,  1.5322815 ],
       [ 0.73741505, -0.10053383,  1.12048315,  1.27072563],
       [ 0.73741505,  0.36346846,  0.72385195,  1.00916975],
       [-1.01139534,  0.59546961, -1.37262727, -1.34483313],
       [ 0.97058977,  0.

In [25]:
x_train,x_test = torch.tensor(x_train,dtype=torch.float32),torch.tensor(x_test,dtype=torch.float32)
y_train,y_test = torch.tensor(y_train,dtype=torch.float32),torch.tensor(y_test,dtype=torch.float32)

C:\Users\Ali Burhan\AppData\Local\Temp\ipykernel_22028\1185095784.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train,y_test = torch.tensor(y_train,dtype=torch.float32),torch.tensor(y_test,dtype=torch.float32)


In [26]:
x_train

tensor([[-1.0114,  0.8275, -1.2593, -1.0833],
        [ 0.5042,  0.5955,  0.4972,  0.4861],
        [-0.8948,  0.8275, -1.3160, -1.3448],
        [-1.2446, -0.1005, -1.3726, -1.4756],
        [ 0.9706,  0.1315,  0.4972,  0.3553],
        [-1.1280, -1.2605,  0.3839,  0.6168],
        [ 2.0199, -0.1005,  1.5738,  1.1399],
        [ 1.0872,  0.3635,  1.1771,  1.4015],
        [ 1.0872, -0.5645,  0.5539,  0.2245],
        [ 0.9706,  0.1315,  0.3272,  0.2245],
        [-0.3119, -0.5645,  0.6105,  1.0092],
        [-1.1280,  0.1315, -1.3160, -1.3448],
        [-0.0787, -0.5645,  0.7239,  1.5323],
        [ 0.7374, -0.1005,  1.1205,  1.2707],
        [ 0.7374,  0.3635,  0.7239,  1.0092],
        [-1.0114,  0.5955, -1.3726, -1.3448],
        [ 0.9706,  0.1315,  1.0072,  1.5323],
        [ 0.5042, -0.3325,  1.0072,  0.7476],
        [-0.5450, -0.1005,  0.3839,  0.3553],
        [ 0.2711, -0.3325,  0.4972,  0.2245],
        [-1.7109, -0.3325, -1.3726, -1.3448],
        [-1.4777,  0.8275, -1.3726

In [27]:
class ANN(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(ANN,self).__init__()
        self.fc1 = nn.Linear(input_size,hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size,output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self,x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.softmax(x)
        return x
    




In [28]:
input_size = 4
hidden_size = 10
output_Size = 3

model = ANN(input_size=input_size,hidden_size=hidden_size,output_size=output_Size)

In [29]:
criterian = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [30]:
epochs = 500
for epoch in range(epochs):
    output = model(x_train)
    loss = criterian(output,y_train.argmax(dim=1))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1)%50 == 0:
        print(f"Epoch [{epoch+1}], Loss: [{loss.item():.4f}]")

Epoch [50], Loss: [1.0777]
Epoch [100], Loss: [1.0128]
Epoch [150], Loss: [0.9285]
Epoch [200], Loss: [0.8465]
Epoch [250], Loss: [0.7899]
Epoch [300], Loss: [0.7540]
Epoch [350], Loss: [0.7281]
Epoch [400], Loss: [0.7077]
Epoch [450], Loss: [0.6900]
Epoch [500], Loss: [0.6742]


In [31]:
# Testing
with torch.no_grad():
    test_outputs = model(x_test)
    _, predicted = torch.max(test_outputs, 1)
    _, actual = torch.max(y_test, 1)
    accuracy = (predicted == actual).sum().item() / len(actual)
    print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 100.00%
